language: zh

pipeline:
- name: JiebaTokenizer            # 分词组件
- name: LanguageModelFeaturizer   # 特征提取组件
  model_name: "bert"
  model_weights: "bert-base-chinese"

# 意图分类
- name: DIETClassifier
- name: FallbackClassifier
  threshold: 0.3
# ############################
# Response Selector相关配置
#- intent: 617, training examples: 178
- name: ResponseSelector
  retrieval_intent: '617'
  scale_loss: false
  epochs: 1000


# ##################
# policies 相关配置
# ##################
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 30
  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: "action_default_fallback"



